### ISSUE TITLE
privacy/cookies

### ISSUE THREAD

**Issue by enterprise888** [privacy/cookies#5]

**Comment by isaac0731** [comment]
- [ ] K[![image](https://user-images.githubusercontent.com/70382548/201504168-18b12e52-9e2c-4dfe-b69c-8a8744feb888.jpeg)]()

**Comment by isaac0731** [comment]
> - [ ] K[![image](https://user-images.githubusercontent.com/70382548/201504168-18b12e52-9e2c-4dfe-b69c-8a8744feb888.jpeg)]()
